trigger:
  - main  # Adjust branch as needed

pool:
  vmImage: 'ubuntu-latest'  # Change to 'windows-latest' or 'macos-latest' if needed

jobs:
- job: Run_Tests
  displayName: 'Run Unit Tests'
  steps:
    - task: NodeTool@0  # Correct task name for setting up Node.js
      inputs:
        versionSpec: '18.x'  # Specify Node.js version

    - script: |
        npm install
        npm test
      displayName: 'Install Dependencies & Run Tests'

- job: Build_Deploy
  displayName: 'Build and Deploy'
  dependsOn: Run_Tests  # Runs only if tests pass
  condition: succeeded()  # Ensures it only runs if the previous job succeeds
  steps:
    - task: NodeTool@0  # Ensure Node.js is available
      inputs:
        versionSpec: '18.x'

    - script: |
        npm install
        npm run build
      displayName: 'Build Application'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
