trigger:
  - main  # Adjust branch as needed

pool:
  vmImage: 'ubuntu-latest'  # Use Windows or macOS if required

jobs:
- job: Run_Tests
  displayName: 'Run Unit Tests'
  steps:
    - task: UseNode@2
      inputs:
        version: '18.x'  # Adjust Node.js version if needed

    - script: |
        npm install
        npm test
      displayName: 'Install Dependencies & Run Tests'

- job: Build_Deploy
  displayName: 'Build and Deploy'
  dependsOn: Run_Tests  # This job runs only if tests pass
  condition: succeeded()  # Ensures it only runs if the previous job succeeds
  steps:
    - script: |
        npm install
        npm run build
      displayName: 'Build Application'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

